"""empty message

Revision ID: 70aab032d357
Revises: 
Create Date: 2021-08-01 20:38:28.350508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70aab032d357'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
